Quiz/urls.py
from django.urls import path
from Quiz.views import student_code_for_next_quiz as code,createQuiz

app_name = "quiz"

urlpatterns = [
    path('quiz/',createQuiz, name="createQuiz"),
    #path('quiz_created', quizCreated, name="quiz_created"),
]

SmartQuiz/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('',include('Quiz.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from users import views
from django.urls import path

app_name = "users"
urlpatterns = [
    path('profile/', views.profile_create, name="profile_create"),
    path('userprofile/',views.user_profile, name="user_profile"),
]

Quiz/models.py
from django.db import models
from datetime import datetime,timedelta
from django.utils import timezone

# Create your models here.

class quiz(models.Model):
    name = models.CharField(max_length=100,blank=False)
    created_by = models.CharField(max_length=200)
    date_of_starting = models.DateField(default=timezone.now)
    date_of_ending = models.DateField(default=timezone.now)
    no_of_questions = models.IntegerField(blank=False)
    duration = models.IntegerField(default=180)
    time_of_starting = models.TimeField(default=datetime.now()+timedelta(hours=1))
    time_of_ending = models.TimeField(default=datetime.now()+timedelta(hours=4))

    class Meta:
        verbose_name = 'quiz'
        verbose_name_plural = 'quizzes'

    def __str__(self):
        return "{} by {}".format(self.name,self.created_by)
        

class question(models.Model):
    quiz = models.ForeignKey(quiz, on_delete=models.CASCADE)
    question = models.CharField(max_length=300)
    answer = models.CharField(max_length=200)
    a = models.CharField(max_length=200)
    b = models.CharField(max_length=200)
    c = models.CharField(max_length=200)
    d = models.CharField(max_length=200)

    def __str__(self):
           return "{} {}".format(self.quiz.name, self.question)

users/models.py
from django.db import models


class Profile(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    registration_number = models.CharField(max_length=9, blank=True)
    phone_number = models.CharField(max_length=10)
    profile_picture = models.ImageField(upload_to="profile_pictures",blank=True)
    email = models.EmailField()
    role_choices = (
        ('teacher', 'Teacher'),
        ('student', 'Student'),
    )
    role = models.CharField(max_length=7,choices=role_choices)

    def __str__(self):
        if self.registration_number=='':
            return "{} {}".format(self.role,str(self.first_name)+" "+str(self.last_name))
        else:
            return "{} {} {}".format(self.registration_number,self.role, str(self.first_name)+" "+str(self.last_name))

Quiz/forms.py
from django.forms import ModelForm
from Quiz.models import quiz


class QuizForm(ModelForm):
    class Meta:
        model = quiz
        fields = "__all__"

users/forms.py
# from django import forms
# from django.contrib.auth.forms import UserCreationForm, UserChangeForm
# from .models import CustomUser


# class CustomUserCreationForm(UserCreationForm):

#     class Meta(UserCreationForm):
#         model = CustomUser
#         fields = ('username', 'email')


# class CustomUserChangeForm(UserChangeForm):

#     class Meta:
#         model = CustomUser
#         fields = UserChangeForm.Meta.fields

Quiz/views.py
from django.shortcuts import render,redirect
import random
import string
from django.contrib import messages
from django.http import HttpResponse
from users.models import Profile
from Quiz.forms import QuizForm
# Create your views here.



def student_code_for_next_quiz(request):
    message = randomString(codelength)
    return message

def randomString(stringLength=6):
    """Generate a random string of fixed length """
    letters = string.ascii_lowercase
    number = random.randint(10 ** (10-stringLength), 10 ** (11-stringLength)-1)
    k = ''.join(random.choice(letters) for i in range(stringLength))
    return k+str(number)

def createQuiz(request):
    if request.user.is_authenticated:
        newUser = Profile.objects.get(email=request.user.email)
        if newUser:
            if newUser.role=="teacher":
                if request.method == "POST":
                    form = QuizForm(request.POST)
                    if form.is_valid():
                        form.save()
                        return HttpResponse("Success!")
                    else:
                        print(form.errors) 
                else:
                    form = QuizForm()
                    return render(request, 'Quiz/createQuiz.html', {'form': form})
            else:
                return HttpResponse("Response to students denied!")
    else:
        return redirect("/accounts/login")

# def quizCreated(request):
#     k = quiz.objects.filter(role="teacher")

                            

users/views.py
from django.shortcuts import render,HttpResponse,redirect
from . models import  Profile


def profile_create(request):
        if request.method=="POST":
                first_name = request.POST.get("First Name")
                last_name = request.POST.get("Last Name")
                registration_number = request.POST.get("Registration Number")
                phone_number = int(request.POST.get("Phone Number"))
                profile_picture = request.POST.get("Profile Picture")
                email = request.user.email
                role = request.POST.get("role")
                k = Profile(first_name,last_name,registration_number,phone_number,profile_picture,email,role)
                k.save()
                return redirect("users:user_profile",permanent=True)
                
        elif request.user.is_authenticated:
                k = Profile.objects.filter(email=request.user.email)
                if len(k)==0:
                        return render(request,"users/create_profile.html")
                else:
                        return redirect("users:user_profile")
                
        else:
                return redirect("/accounts/login",permanent=True)

def user_profile(request):
        if request.user.is_authenticated:
                k = Profile.objects.get(email=request.user.email)
                if k.role == "student" and k.registration_number!="":
                        profile = [k.first_name,k.last_name,k.registration_number,k.phone_number,k.profile_picture,k.email,k.role]
                        return render(request,"users/user_profile.html",context={"profile":profile})
                elif k.role == "teacher" and k.registration_number=="":
                        profile = [k.first_name, k.last_name, k.registration_number,k.phone_number, k.profile_picture, k.email, k.role]
                        return render(request, "users/user_profile.html", context={"profile": profile})
                else:
                        return HttpResponse("Error in user_profile handling!")

        else:
                return redirect("/accounts/login")
                

    

Quiz/templates/Quiz/createQuiz.html
<html>
<head>
<title>Create Quiz</title>
</head>
<body>
<form method="POST" action={% url "quiz:createQuiz" %}>
{% csrf_token %}
<h1>Quiz Creation Form</h1>
{{ form.as_p }}
<input type="submit" value="Submit">
</form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
  
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
        <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
        {% else %}
        <li><a href="{% url 'account_login' %}">Sign In</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
    <div style="text-align:center">
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
    </div>
  </body>
</html>

users/templates/users/create_profile.html
<html>
<head>
<title>Profile Page</title>
</head>
<body>
<form method="POST" action={% url 'users:profile_create' %}>
{% csrf_token %}
First Name : <input type="text" name="First Name"><br>
Last Name : <input type="text" name="Last Name"><br>
Registration Number<input type="text" name="Registration Number">(*leave out if you are a teacher)<br>
Email id : {{ user.email }}<br>
Profile Picture : <input type="file" accept=".jpg,.jpeg,.png" name="Profile Picture"><br>
Phone Number : <input type="number" name="Phone Number"><br>
<p>Select user role:</p>
<div>
  <input type="radio" id="student" name="role" value="student" checked>
  <label for="student">Student</label>
</div>
<div>
  <input type="radio" id="teacher" name="role" value="teacher">
  <label for="teacher">Teacher</label>
</div>
<input type="submit" value="Submit">
</form>
</html>

users/templates/users/user_profile.html
<html>
<head>
<title>Profile Page</title>
</head>
<body>
<div style="text-align:center">
<img src="{{ profile.4.url}}" width="200" height="200" ><br>
Hello ! {{ profile.0 }} {{ profile.1}}<br>
First Name : {{ profile.0 }} <br>
Last Name : {{ profile.1}}<br>
{% if profile.2 %}
Registration Number: {{ profile.2}}<br>
{% endif %}
Email id : {{ profile.5}}<br>
Phone Number : {{ profile.3}}<br>
Role : {{profile.6}}


</div>

{% if profile.6 == 'student' %}
<a href="quiz:students_quiz">Quizzes</a>
<a href="quiz:students_results">Results</a>
{% endif %}
{% if profile.6 == 'teacher' %}
<a href="quiz:quiz_created">Quizzes created</a>
<a href="quiz:results_of_quiz">Results of quizzes</a>
{% endif %}

</body>
</html>